---
# Example demonstrating selective feature usage with toggle variables

# Example 1: Only disk formatting, no monitoring
- name: Format disks only
  hosts: all
  vars:
    enable_disk_discovery: false
    enable_smart_monitoring: false
    enable_ssd_trim: false
    enable_disk_formatting: true
    disks_to_format:
      - device: /dev/sdb
        filesystem: ext4
        mount_point: /mnt/data
        mount_options: defaults,noatime
  roles:
    - ansible-disks

---
# Example 2: Only SMART monitoring, no disk formatting
- name: SMART monitoring only
  hosts: all
  vars:
    enable_disk_discovery: true
    enable_smart_monitoring: true
    enable_ssd_trim: true
    enable_disk_formatting: false
  roles:
    - ansible-disks

---
# Example 3: All features (default behavior)
- name: All features enabled
  hosts: all
  vars:
    # These are the defaults, but shown for clarity
    enable_disk_discovery: true
    enable_smart_monitoring: true
    enable_ssd_trim: true
    enable_disk_formatting: true
    disks_to_format:
      - device: /dev/sdb
        filesystem: ext4
        mount_point: /mnt/data1
      - device: /dev/sdc
        filesystem: ext4
        mount_point: /mnt/data2
  roles:
    - ansible-disks
