---
# tasks file for server-disks

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: configure crons
  template: src={{ item.cron_scripts }} dest={{ item.cron_path }} mode={{ item.mode }}
  with_items: '{{ CRONS }}'
  tags: template-crons
